#!/bin/bash
cd latex
cp -rf ../template/* .
cp -rf ../contents/img .
#ls -al img
pandoc -t latex ../contents/0-preface*.markdown -o preface.tex
pandoc -t latex ../contents/1-chapter*.markdown -o chapters.tex
pandoc -t latex ../contents/2-appendix*.markdown -o appendix.tex
if [ "X$OS" == "XWindows_NT" ]; then
	echo "windows platform"
	cp template-win.tex 2014books.tex
else
	echo "unix platform"
	cp template.tex 2014books.tex
fi
#exit
xelatex 2014books.tex
xelatex 2014books.tex
xelatex 2014books.tex
cp 2014books.pdf ..
echo
echo
echo "Done!"
